apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Use the staging server for testing to avoid hitting rate limits
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # IMPORTANT: Replace with a valid email address
    email: massimiliano.dacunzo@hotmail.com
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-staging-account-key
    solvers:
    - http01:
        ingress:
          # The ingress class used by AKS Web App Routing
          ingressClassName: webapprouting.kubernetes.azure.com
