import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :privee_web, PriveeWeb.Endpoint,
  # Dynamic host configuration based on deployment platform
  url: [
    host: System.get_env("PHX_HOST") || "privee.fly.dev",
    port: String.to_integer(System.get_env("PHX_PORT") || "80")
  ],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, :api_client, Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# OpenTelemetry configuration for production
config :opentelemetry, :processors,
  otel_batch_processor: %{
    exporter: {:otel_exporter_otlp, %{
      protocol: :grpc,
      endpoints: ["https://otlp-gateway-prod-eu-west-2.grafana.net:443"],
      headers: []
    }}
  }

config :opentelemetry,
  resource: [
    service: %{
      name: "privee",
      version: "0.1.0"
    },
    deployment: %{
      environment: "production"
    }
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
