import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :privee_web, PriveeWeb.Endpoint,
  # Dynamic host configuration based on deployment platform
  url: [
    # host: System.get_env("PHX_HOST") || "privee.fly.dev",
    host: "privee.northeurope.cloudapp.azure.com",
    port: String.to_integer(System.get_env("PHX_PORT") || "80")
  ],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, :api_client, Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
