# This resource pulls privee-tls from Key Vault as PEM, syncs to a kubernetes.io/tls secret named ingress-tls, and auto‑rotates.
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-tls
  namespace: default
spec:
  provider: azure
  parameters:
    keyvaultName: Privee-KV
    tenantId: b4a3e2d3-2d99-4b3e-a15e-5a85d655c544 # az account show --query tenantId -o tsv
    cloudName: AzurePublicCloud
    clientID: ${UAMI_CLIENT_ID} # az identity show -g "$AKS_RG" -n "privee-kv-wi" --query clientId -o tsv
    objects: |
      array:
        - |
          objectName: privee-tls
          objectType: secret
          contentType: application/x-pem-file
    rotationPollInterval: 2h
  secretObjects:
    - secretName: ingress-tls
      type: kubernetes.io/tls
      data:
        - objectName: privee-tls
          key: tls.crt
        - objectName: privee-tls-key
          key: tls.key