name: load-tooling
description: "Loads the Elixir, Erlang tooling"

inputs:
  otp:
    description: "OTP version"
    required: true
    default: "28.0.1"
  elixir:
    description: "Elixir version"
    required: true
    default: "1.18.4"
  node:
    description: "Node version"
    required: true
    default: "18"

runs:
  using: "composite"

  steps:
    - name: Loading Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ inputs.otp }}
        elixir-version: ${{ inputs.elixir }}

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}

    # Step: installing inotify-tools to enable LiveView reloading to perform the tests.
    - name: Install OS dependencies
      shell: bash
      run: sudo apt install inotify-tools
