name: load-tooling
description: "Loads the Elixir, Erlang and Zig tooling"

inputs:
  otp:
    description: "OTP version"
    required: true
    default: "27.1.2"
  elixir:
    description: "Elixir version"
    required: true
    default: "1.17.3"
  zig:
    description: "Zig compiler version"
    required: true
    default: "0.13.0"
  node:
    description: "Node version"
    required: true
    default: "18"

runs:
  using: "composite"

  steps:
    - name: Loading Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ inputs.otp }}
        elixir-version: ${{ inputs.elixir }}

    - name: Loading Zig compiler
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: ${{ inputs.zig }}

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}

    # Step: installing inotify-tools to enable LiveView reloading to perform the tests.
    - name: Install OS dependencies
      shell: bash
      run: sudo apt install inotify-tools
