name: build-nifs
description: 'Build Zig NIFs in the project'

permissions:
  contents: read

runs:
  using: "composite"

  steps:
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.11.0

    - name: Building NIFs
      shell: bash
      run: zig build --build-file nifs/build.zig && zig fmt --check ./nifs
