name: build-nifs
description: "Build Zig NIFs in the project"

inputs:
  zig:
    description: "Zig compiler version"
    required: true
    default: "0.14.0"

runs:
  using: "composite"

  steps:
    - name: Building NIFs
      shell: bash
      working-directory: nifs
      run: zig build -- /opt/hostedtoolcache/otp/ubuntu-24.04/OTP-28.0.1/x64/erts-16.0.1/include
