when:
  - event: push
    branch: main

depends_on:
  - check-elixir
  - check-node

steps:
  - name: deploy
    image: debian:bookworm-slim
    environment:
      FLY_API_TOKEN:
        from_secret: fly_api_token
    commands:
      - apt-get update -y && apt-get install -y curl
      - curl -L https://fly.io/install.sh | sh
      - export FLYCTL_INSTALL="/root/.fly"
      - export PATH="$FLYCTL_INSTALL/bin:$PATH"
      - flyctl deploy --remote-only
