# SecretProviderClass for Azure Key Vault CSI Driver
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-privee
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "${UAMI_CLIENT_ID}"
    keyvaultName: "${KEYVAULT_NAME}"
    tenantId: "${TENANT_ID}"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: privee-secret-key-base
          objectType: secret
          objectVersion: ""
        - |
          objectName: postgres-user
          objectType: secret
          objectVersion: ""
        - |
          objectName: postgres-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: postgres-db
          objectType: secret
          objectVersion: ""
  secretObjects:
  - secretName: privee-app-secret
    type: Opaque
    data:
    - objectName: privee-secret-key-base
      key: SECRET_KEY_BASE
  - secretName: postgres-secret
    type: Opaque
    data:
    - objectName: postgres-user
      key: POSTGRES_USER
    - objectName: postgres-password
      key: POSTGRES_PASSWORD
    - objectName: postgres-db
      key: POSTGRES_DB