name: Elixir CI - Compilation
description: "Runs compilation checks on the codebase."

permissions:
  contents: read

runs:
  using: "composite"

  steps:
    # Step: Compile the project treating any warnings as errors.
    # Customize this step if a different behavior is desired.
    - name: Compiles without warnings
      shell: bash
      run: mix compile --warnings-as-errors
