name: Run Azure Login with Managed Identity

# on:
#   workflow_run:
#     workflows: ["Elixir CI - Compilation"]
#     types:
#       - completed
on: [push]

env:
  ACR_RESOURCE_GROUP: Privee
  AZURE_CONTAINER_REGISTRY: Privee
  CLUSTER_NAME: Privee
  CLUSTER_RESOURCE_GROUP: Privee
  CONTAINER_NAME: privee
  DEPLOYMENT_MANIFEST_PATH: |
    ./k8s-deployment.yml

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2.1.1
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Build image on ACR
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az configure --defaults acr=${{ env.AZURE_CONTAINER_REGISTRY }}
            az acr build -t -t ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }}

      - name: Gets K8s context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Deploys application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          images: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
          namespace: default