name: Run Azure Login with Managed Identity

# on:
#   workflow_run:
#     workflows: ["Elixir CI - Compilation"]
#     types:
#       - completed
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v2.1.1
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      # - name: Log in to Azure CLI using Managed Identity
      #   run: |
      #     az login --identity
      #     az acr login --name ${{ secrets.ACR_NAME }} --identity

      - name: Build and push Docker image
        run: |
          echo whoami
          docker build -t privee.azurecr.io/privee:${{ github.sha }} .
          docker push privee.azurecr.io.azurecr.io/privee:${{ github.sha }}

      - name: Logout from Azure CLI
        run: az logout