name: Deploy to Azure

on:
  workflow_run:
    workflows: ["Privee Main CI/CD pipeline"]
    types:
      - completed
    branches: [main]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  azure-deployment:
    name: Deploy to Azure
    runs-on: ubuntu-24.04
    # Only run if the main CI workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      RESOURCE_GROUP: privee-dev-rg
      AZURE_CONTAINER_REGISTRY: priveeregistry
      REGISTRY_URL: priveeregistry.azurecr.io
      PROJECT_NAME: privee
      CLUSTER_NAME: privee-aks
      CONTAINER_NAME: privee
      DEPLOYMENT_MANIFEST_PATH: |
        ./.azure/k8s/deployment.yml
      # Set the Azure-specific host for Phoenix compilation
      PHX_HOST: privee.northeurope.cloudapp.azure.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Build image on ACR
      #   uses: azure/CLI@v2
      #   with:
      #     inlineScript: |
      #       cd ${{ github.workspace }}
      #       az configure --defaults acr=${{ env.AZURE_CONTAINER_REGISTRY }}
      #       az acr build -t ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }} .

      - name: Log in to ACR using OIDC session
        run: |
          az acr login --name "${AZURE_CONTAINER_REGISTRY}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:latest
          build-args: |
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VCS_REF=${GITHUB_SHA}
            PHX_HOST=${{ env.PHX_HOST }}
            ENABLE_DB_SSL=true

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1.2
        with:
          kubelogin-version: 'v0.0.24'

      - name: Gets K8s context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Deploys application
        uses: Azure/k8s-deploy@v5
        with:
          namespace: default
          action: deploy
          images: |
            ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
          manifests: |
            ${{ env.DEPLOYMENT_MANIFEST_PATH }}