name: Privee Main CI/CD pipeline

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build:
    # The `runs-on` configuration must be set only at the top level workflow execution.
    runs-on: ubuntu-24.04

    name: CI Build and test Erlang ${{ matrix.otp }} / Elixir ${{ matrix.elixir }} / Node ${{ matrix.node }} / Zig ${{ matrix.zig }}

    env:
      MIX_ENV: test

    services:
      db:
        image: "postgres:11"
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: "postgres"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      # Specify the OTP and Elixir versions to use when building
      # and running the workflow steps.
      matrix:
        otp: ["27.2.4"]
        elixir: ["1.18.2"]
        zig: ["0.13.0"]
        node: ["22"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Loading tooling
        uses: ./.github/actions/load-tooling
        with:
          otp: ${{ matrix.otp }}
          elixir: ${{ matrix.elixir }}
          zig: ${{ matrix.zig }}
          node: ${{ matrix.node }}

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build NIfs
        uses: ./.github/actions/build-nifs

      - name: Breakpoint if tests failed
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: MaxDac

      - name: Build PR
        uses: ./.github/actions/compile-pr

      - name: Check PR
        uses: ./.github/actions/check-pr
        with:
          otp: ${{ matrix.otp }}
          elixir: ${{ matrix.elixir }}

      - name: Test PR
        uses: ./.github/actions/test-pr

      - name: Test Client
        uses: ./.github/actions/check-client

  fly-deploy:
    name: Deploy Fly.io app
    runs-on: ubuntu-24.04
    concurrency: deploy-group # optional: ensure only one action runs at a time
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fly.io deployment
        uses: ./.github/actions/fly-deploy
        with:
          fly_api_token: ${{ secrets.FLY_API_TOKEN }}

  azure-deploy:
    name: Deploy application on Azure AKS cluster
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Image build and Azure AKS cluster deployment
        uses: ./.github/actions/azure-deploy
        with:
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          acr-username: ${{ secrets.ACR_USER }}
          acr-password: ${{ secrets.ACR_SECRET }}
