name: Privee PR CI

# on:
#   pull_request:
#     types:
#       - opened
#       - synchronize
#       - reopened

#     branches:
#       - main

# permissions:
#   contents: read

jobs:
  build:
    # The `runs-on` configuration must be set only at the top level workflow execution.
    runs-on: ubuntu-24.04

    name: Pull Request CI Build and test Erlang ${{ matrix.otp }} / Elixir ${{ matrix.elixir }} / Node ${{ matrix.node }} / Zig ${{ matrix.zig }}

    env:
      MIX_ENV: dev

    services:
      db:
        image: "postgres:11"
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: "postgres"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      # Specify the OTP and Elixir versions to use when building
      # and running the workflow steps.
      matrix:
        otp: ["27.2.4"]
        elixir: ["1.18.2"]
        zig: ["0.13.0"]
        node: ["22"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Loading tooling
        uses: ./.github/actions/load-tooling
        with:
          otp: ${{ matrix.otp }}
          elixir: ${{ matrix.elixir }}
          zig: ${{ matrix.zig }}
          node: ${{ matrix.node }}

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build NIfs
        uses: ./.github/actions/build-nifs

      - name: Breakpoint if tests failed
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: MaxDac

      - name: Build PR
        uses: ./.github/actions/compile-pr

      - name: Check PR
        uses: ./.github/actions/check-pr
        with:
          otp: ${{ matrix.otp }}
          elixir: ${{ matrix.elixir }}

      - name: Test PR
        uses: ./.github/actions/test-pr

      - name: Test Client
        uses: ./.github/actions/check-client
