name: Fly.io test deployment

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  fly-deploy:
    name: Deploy Fly.io app
    runs-on: ubuntu-24.04
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fly.io deployment
        uses: ./.github/actions/fly-deploy
        with:
          fly_api_token: ${{ secrets.FLY_API_TOKEN }}
